services:

  postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kilo171polo
      POSTGRES_DB: task_manager
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: auth_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pg_data:
